#!/usr/bin/env bash
set -euo pipefail

# XFI CONNECT installer.
# This script installs only the current XFI CONNECT repository.
# Remote update / upstream synchronization commands are intentionally absent.

INSTALL_DIR="/root/XFI_CONNECT"
VENV_DIR="$INSTALL_DIR/venv"
SERVICE_NAME="xfi-connect"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
AI_ENV_FILE="/etc/xfi-connect.env"

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${CYAN}[XFI CONNECT]${NC} $*"; }
ok() { echo -e "${GREEN}[OK]${NC} $*"; }
fail() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || fail "Запустите установщик от root."

BOT_TOKEN="${1:-}"
ADMIN_ID="${2:-}"

if [ -z "$BOT_TOKEN" ]; then
    read -r -p "BOT_TOKEN: " BOT_TOKEN
fi
if [ -z "$ADMIN_ID" ]; then
    read -r -p "ADMIN_ID: " ADMIN_ID
fi
[[ "$ADMIN_ID" =~ ^[0-9]+$ ]] || fail "ADMIN_ID должен быть числом."

log "Установка системных зависимостей"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq python3-venv python3-pip git >/dev/null

if [ -d "$INSTALL_DIR" ]; then
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
fi

if [ ! -d "$INSTALL_DIR/.git" ]; then
    log "Клонирование XFI CONNECT"
    rm -rf "$INSTALL_DIR"
    git clone --depth 1 https://github.com/deilja/XFI_CONNECT.git "$INSTALL_DIR"
else
    log "Используется существующая рабочая копия XFI CONNECT"
fi

cd "$INSTALL_DIR"

[ -f config.py.example ] || fail "config.py.example не найден."

if [ ! -f config.py ]; then
    cp config.py.example config.py
    python3 - "$BOT_TOKEN" "$ADMIN_ID" <<'PY'
from pathlib import Path
import sys

path = Path("config.py")
text = path.read_text(encoding="utf-8")
text = text.replace('BOT_TOKEN = "ВАШ_ТОКЕН_БОТА"', f'BOT_TOKEN = {sys.argv[1]!r}')
text = text.replace('    12345678,', f'    {sys.argv[2]},', 1)
path.write_text(text, encoding="utf-8")
PY
    ok "config.py создан"
else
    python3 - <<'PY'
from pathlib import Path

path = Path("config.py")
text = path.read_text(encoding="utf-8")
old = 'GITHUB_REPO_URL = ""'
if old in text:
    text = text.replace(old, 'GITHUB_REPO_URL = "https://github.com/deilja/XFI_CONNECT.git"', 1)
    path.write_text(text, encoding="utf-8")
    print("GITHUB_REPO_URL migrated to XFI CONNECT")
PY
    ok "Существующий config.py сохранён; updater привязан к XFI CONNECT"
fi

log "Настройка XFI AI Gateway"
if [ ! -f "$AI_ENV_FILE" ]; then
    cat > "$AI_ENV_FILE" <<'EOF'
# XFI AI Gateway connection for XFI CONNECT.
# Set XFI_AI_API_KEY to the gateway key generated by XFI AI.
XFI_AI_BASE_URL=http://127.0.0.1:8091
XFI_AI_API_KEY=
XFI_AI_MODEL=
XFI_AI_TIMEOUT=45
EOF
    chmod 600 "$AI_ENV_FILE"
    ok "Создан $AI_ENV_FILE"
else
    chmod 600 "$AI_ENV_FILE"
    ok "Существующий $AI_ENV_FILE сохранён"
fi

log "Настройка Python окружения"
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
"$VENV_DIR/bin/pip" install -r requirements.txt >/dev/null

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=XFI CONNECT Telegram Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=-$AI_ENV_FILE
ExecStart=$VENV_DIR/bin/python $INSTALL_DIR/main.py
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME" >/dev/null
systemctl restart "$SERVICE_NAME"
sleep 2

if systemctl is-active --quiet "$SERVICE_NAME"; then
    ok "XFI CONNECT запущен"
else
    systemctl status "$SERVICE_NAME" --no-pager || true
    journalctl -u "$SERVICE_NAME" -n 50 --no-pager || true
    fail "Не удалось запустить XFI CONNECT."
fi

echo
echo "Установка завершена."
echo "Каталог: $INSTALL_DIR"
echo "Сервис:  $SERVICE_NAME"
echo "AI env:  $AI_ENV_FILE"
echo "Статус:  systemctl status $SERVICE_NAME"
echo "Логи:    journalctl -u $SERVICE_NAME -f"
